interface_registry:
  messages: []
  services:
  - file_name: ScheduleCrud.srv
    file_kind: srv
    type_name: ScheduleCrud
    uploaded_at: '2026-07-15T02:51:10.431218+00:00'
    raw_text: '# cmd: 1=CREATE, 2=READ, 3=UPDATE, 4=DELETE, 5=LIST

      uint8 cmd


      string table_name


      # CREATE/UPDATE용 데이터 (UPDATE는 scheduling_id 포함해서 전달)

      rths_interfaces/CleaningSchedule[] items


      # LIST 옵션

      bool only_active

      string where

      string options


      ---

      bool success

      string message



      # LIST 결과(목록)

      rths_interfaces/CleaningSchedule[] items


      '
    parsed:
      request:
      - type: uint8
        raw_line: uint8 cmd
        name: cmd
      - type: string
        raw_line: string table_name
        name: table_name
      - type: rths_interfaces/CleaningSchedule[]
        raw_line: rths_interfaces/CleaningSchedule[] items
        name: items
      - type: bool
        raw_line: bool only_active
        name: only_active
      - type: string
        raw_line: string where
        name: where
      - type: string
        raw_line: string options
        name: options
      response:
      - type: bool
        raw_line: bool success
        name: success
      - type: string
        raw_line: string message
        name: message
      - type: rths_interfaces/CleaningSchedule[]
        raw_line: rths_interfaces/CleaningSchedule[] items
        name: items
  actions:
  - file_name: CanControl.action
    file_kind: action
    type_name: CanControl
    uploaded_at: '2026-07-15T02:49:38.735913+00:00'
    raw_text: '# Goal

      uint8 node_id

      uint8 port

      uint32 value

      uint8 retries

      uint32 timeout_ms


      ---

      # Result

      bool success

      uint8 ctrl_code

      uint32 response_can_id

      string message


      ---

      # Feedback

      string stage

      uint8 attempt

      string detail

      '
    parsed:
      goal:
      - type: uint8
        raw_line: uint8 node_id
        name: node_id
      - type: uint8
        raw_line: uint8 port
        name: port
      - type: uint32
        raw_line: uint32 value
        name: value
      - type: uint8
        raw_line: uint8 retries
        name: retries
      - type: uint32
        raw_line: uint32 timeout_ms
        name: timeout_ms
      result:
      - type: bool
        raw_line: bool success
        name: success
      - type: uint8
        raw_line: uint8 ctrl_code
        name: ctrl_code
      - type: uint32
        raw_line: uint32 response_can_id
        name: response_can_id
      - type: string
        raw_line: string message
        name: message
      feedback:
      - type: string
        raw_line: string stage
        name: stage
      - type: uint8
        raw_line: uint8 attempt
        name: attempt
      - type: string
        raw_line: string detail
        name: detail
